name: Terraform Apply for DNS Zones

on:
  push:
    branches:
      - main
    paths:
      - 'dns_zones/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y python3-yaml
  
      - name: Combine individual YAML files into master YAML
        run: |
          cat ./dns_zones/*.yml > ./combined_zones.yml
          cat combined_zones.yml

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
