name: Sync Route53

on:
  push:
    branches: [ main ]

jobs:
    terraform:
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v2
        - name: Terraform init
          run: terraform init
        - name: Terraform apply
          run: terraform apply -auto-approve
