name: Validate

on:
  pull_request:
    paths:
      - '**.yml'
      - '**.tf'

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        - name: Install yamllint
          run: pip install yamllint
        - name: Lint YAML
          run: yamllint dns_zones
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
        - name: Terraform fmt
          working-directory: terraform
          run: terraform fmt -check

    plan:
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
        - name: Terraform init
          working-directory: terraform
          run: terraform init
        - name: Terraform validate
          working-directory: terraform
          run: terraform validate
        - name: Terraform plan
          working-directory: terraform
          run: terraform plan -no-color -input=false
